FROM python:3

ADD plotting_functions_for_cloud.py /
ADD requirements.txt /

RUN pip install -r requirements.txt

ENV PYTHONPATH "${PYTHONPATH}:/usr/src/app"

#CMD ["curl", "169.254.170.2\$AWS_CONTAINER_CREDENTIALS_RELATIVE_URI"]
CMD ["python", "plotting_functions_for_cloud.py"]

#docker build -t newsletter-generator .